name: ecommerce
services:
  postgres:
    image: postgres:14
    container_name: ecommerce-postgres
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'ecommerce']
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_USER: root
      POSTGRES_DB: ecommerce

  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 30s
      retries: 3
